### ISSUE TITLE
Assign Scrum Roles

### ISSUE THREAD

**Issue by Group2eweb** [ewebgrouptwo/cmr#5]
- [x] Group to assign **roles**

| Role Name | Primary Responsibility | Secondary Responsibility |
| --- | --- | --- |
| **Database Designer** | James | Harrison |
| **Information Architect** | Chimwemwe | Dali |
| **Programmer** | Harrison | James |
| **Web Designer** | George | Harrison |
| **Tester** | Dali | Chimwemwe |
| **Scrum Master** | James | Harrison |
| **Product Owner** | George | Nsendema |

**Comment by JamesChirambo** [comment]
this was done on 3rd March 2016 by the group
